### ISSUE TITLE
Fix color_eyre usage in all examples

### ISSUE THREAD

**Issue by GenericNerdyUsername** [ratatui/ratatui#1277]
The code snippet
```rs
    // convert from a color_eyre EyreHook to a eyre ErrorHook
    let eyre_hook = eyre_hook.into_eyre_hook();
    eyre::set_hook(Box::new(
        move |error: &(dyn std::error::Error + 'static)| {
            tui::restore().unwrap();
            eyre_hook(error)
        },
    ))?;
```
makes the hook that converts errors into reports reset the terminal state, even if no panic has occurred (the panic just before is fine). This means that if a report is created, the program behaves unexpectedly.

**Comment by joshka** [comment]
https://github.com/ratatui-org/ratatui/pull/1289/ pretty much fixes this up for all examples. The use pattern is pretty simple:
```rust
fn main() -> Result<()> {
    color_eyre::install()?;
    let terminal = ratatui::init();
    let app_result = App::new().run(terminal);
    ratatui::restore();
    app_result
}
```
`ratatui::init()` handles setting up the panic handler correctly.

**Comment by orhun** [comment]
I think this can be closed now.

**Comment by joshka** [comment]
yup

**Comment by Android789515** [comment]
The example [here](https://ratatui.rs/recipes/apps/color-eyre/) is not updated.

**Comment by Android789515** [comment]
> The example [here](https://ratatui.rs/recipes/apps/color-eyre/) is not updated.

My mistake. I assumed it wasn't because the code did not match https://github.com/ratatui/ratatui/issues/1277#issuecomment-2290482268. Looks like it is up to date.
