### ISSUE TITLE
Sparkline: Add support for empty bar style

### ISSUE THREAD

**Issue by fujiapple852** [ratatui/ratatui#1325]
## Problem

The `Sparkline` widget takes a `&[64]` and shows a blank vertical bar for `0` values; it is desirable to be able to show `0` samples with an alternative styling to highlight them.

Today:

![image](https://github.com/user-attachments/assets/a32867e0-df31-4d4d-bd43-c0591c29c36f)

Desired:

![image](https://github.com/user-attachments/assets/73ccf43b-933a-463b-99d4-d59051c4c3a1)

## Solution

PR: https://github.com/ratatui-org/ratatui/pull/1326

Note that this solution is purely additive, there is no change to behaviour or rendering of existing `Sparkline` users.

## Alternatives

As well as controlling the style of empty bars, it may also be desirable to control the symbol as well, though I have need of that feature today.

## Additional context

In [Trippy](https://github.com/fujiapple852/trippy), we use the `Sparkline` to show a history of samples and missing samples (i.e. lost packets) are represented by zero and are therefore rendered (or rather, not rendered) as a blank vertical bar.  By styling zero values in an alternative way this can be highlighted to the user.

See https://github.com/fujiapple852/trippy/issues/1247

**Comment by joshka** [comment]
Great idea - one step further though, what would think about having a symbol to represent this as well? e.g. `░` / `▒` / `▓`

**Comment by fujiapple852** [comment]
@joshka we could perhaps add a `empty_bar_symbol(char)`?  I don't think adding `empty_bar_symbol_set(symbols::bar::Set)` would add much value but we could do that.

**Comment by joshka** [comment]
In the PR I wrote:

>Looking at this line in particular, it sort of suggests an idea that this could be more flexible to implement in a way that each data item is Option instead of treating 0 as a special case. This would allow the Sparkline to indicate both 0 data and missing data points on the same graph. This might be more difficult to work out a good migration strategy for however - likely adding a new method to support this (unless there's a really good way to make the method accept both datasets - I can't see an obvious one though)

and

>Overall I'm ok with this idea (it's pretty reasonable), but I'd like to explore the idea of adding a custom symbol for this a bit before committing to this.

It makes sense to keep the feature discussion over on this issue rather than splitting them. 

Something in general that I'd like to think a bit more about is how to do some more things like this where the per item config is a bit more dynamic rather than static (i.e. the application code runs per item when rendering and can inject style info, etc.)

In the short term though, this seems like a good idea. I'd like to get some ideas from the other maintainers though too to help gauge where makes sense to make this configurable.

**Comment by fujiapple852** [comment]
> it sort of suggests an idea that this could be more flexible to implement in a way that each data item is Option instead of treating 0 as a special case. This would allow the Sparkline to indicate both 0 data and missing data points on the same graph.

I thought the same but decided that may be to invasive so parked it.  I sketched up the-obvious-thing to support this in a way that doesn't impacting the existing API:

```rust
pub fn data(mut self, data: impl Into<SparklineData>) -> Self {
    self.data = data.into();
    self
}

#[derive(Debug, Default, Clone, Eq, PartialEq)]
pub struct SparklineData(Vec<Option<u64>>);

impl SparklineData {
    pub fn iter(&self) -> Iter<'_, Option<u64>> {
        self.0.iter()
    }
    pub fn len(&self) -> usize {
        self.0.len()
    }
}

impl<'a> From<&'a [u64]> for SparklineData {
    fn from(value: &'a [u64]) -> Self {
        Self(value.iter().copied().map(Some).collect())
    }
}

impl<'a, const N: usize> From<&'a [u64; N]> for SparklineData {
    fn from(value: &'a [u64; N]) -> Self {
        Self(value.iter().copied().map(Some).collect())
    }
}

impl<'a> From<&'a [Option<u64>]> for SparklineData {
    fn from(value: &'a [Option<u64>]) -> Self {
        Self(value.iter().copied().collect())
    }
}

impl<'a, const N: usize> From<&'a [Option<u64>; N]> for SparklineData {
    fn from(value: &'a [Option<u64>; N]) -> Self {
        Self(value.iter().copied().collect())
    }
}
```

I don't think it can be done without taking ownership of the data (outside of unsafe) but happy to be proven wrong.  In fact the `render_sparkline` already clones all the data every time anyway, so i'm sure we can combine these steps and make this change net neutral.

I pushed a 2nd WP commit to show the idea (can squash them later)

**Comment by fujiapple852** [comment]
I've [vendored](https://github.com/fujiapple852/trippy/commit/845d293a282ef63e4270a258caf1d5fe688fb7f0) (with appropriate attribution) the modified version of the `Sparkline` widget in Trippy for now, I plan to remove if/when this work lands in Ratatui.  Let me know how I can help get this over the line.

**Comment by fujiapple852** [comment]
Example of per-bar styling:

<img width="258" alt="Screenshot 2024-09-04 at 9 51 54 PM" src="https://github.com/user-attachments/assets/7ea8b745-56ca-4cbd-83a1-94facd1577a4">

**Comment by orhun** [comment]
very colorful!

**Comment by fujiapple852** [comment]
An interesting follow up to this would be to support different styling _within_ a bar, based on the height.  In that way, you could achieve an effect akin to a graphic equalizer, i.e. this type of thing (random gif I found to illustrate the point, obviously not rendered in ratatui, yet!):

![image](https://github.com/user-attachments/assets/0cb566bf-e424-444d-b641-457d203b71c7)

**Comment by joshka** [comment]
Hrm, that's a neat effect, but I think I'd do that as a custom widget rather than abusing the sparkline too much..

(nerd sniped... https://github.com/joshka/tui-equalizer)

![Made with VHS](https://vhs.charm.sh/vhs-732McVor5Mxwa0IMDh7uP6.gif)

**Comment by fujiapple852** [comment]
Love it!
