### ISSUE TITLE
Performance considerations with using `stderr` in the book

### ISSUE THREAD

**Issue by vyfor** [ratatui/ratatui#1348]
## Problem

I've been trying to make a TUI app using Ratatui for the past few days, but at some point, I started experiencing slow UI renders, as shown below:

https://github.com/ratatui/ratatui/assets/92883017/4dee6113-0e9f-4a20-b755-841317dbe471

Upon investigating further, I noticed that when I was following [this guide](https://ratatui.rs/recipes/apps/terminal-and-event-handler/), I replaced `stdout` with `stderr`. Since `stderr` seems to be unbuffered in most cases, it can cause performance issues.

## Solution

I'd either inform the user that using `stderr` on some terminals may cause performance issues, or switch to using `stdout` altogether. It took me quite some time to trace back the issue, so this is something worth reconsidering.

**Comment by Valentin271** [comment]
Yep good idea, I'm on it.
