### ISSUE TITLE
`Cow<str>` should implement `Into<Title>`

### ISSUE THREAD

**Issue by leslie255** [ratatui/ratatui#1367]
## Description
`Cow<'a, str>` doesn't implement `Into<'a, Title>`.

This causes functions like `Block::title` to not accept `Cow<str>`, despite the fact that [the doc for that function says that it accepts `Cow<str>`](https://github.com/ratatui/ratatui/blob/5635b930c7196ef8f12824341a7bd8b7323aabcd/src/widgets/block.rs#L242).

## To Reproduce
```rs
fn _f() {
  use ratatui::widgets::block::Block;
  use std::borrow::Cow;
  let cow_str: Cow<'static, str> = Cow::Borrowed("hello, world");
  let _ = Block::new()
    .title(cow_str); // Error: the trait bound ratatui::prelude::Line<'_>:
                     // std::convert::From<std::borrow::Cow<'_, str>> is not
                     // satisfied
}
```

## Expected behavior
That the above code should just compile and run normally.

## Screenshots
<img width="1410" alt="Screenshot 2024-09-11 at 22 34 30" src="https://github.com/user-attachments/assets/d8fdbbf9-279a-4ea8-98f8-2fb7c0d3bb22">

## Environment
I don't think this is relevant.

## Additional context
A current workaround is to just do `.title(Span::raw(cow_str))`.

**Comment by joshka** [comment]
We actually want Title to go away sometime soon (and instead just use Line). This would make the title call accept `Into<Line>` which is implemented for `Cow<str>`.

**Comment by orhun** [comment]
@joshka is there a tracking issue for deprecating Title? Should we do that next release?

**Comment by joshka** [comment]
https://github.com/ratatui/ratatui/issues/738

**Comment by joshka** [comment]
Actually reopening. This is due to `Line` not implementing `From<Cow>`
