### ISSUE TITLE
Disambiguating shift keys

### ISSUE THREAD

**Issue by francisdb** [ratatui/ratatui#1369]
## Problem

I'm building a pinball simulator frontend UI and the main keys normally used for navigation are left and right shift / left and right control because that's what the virtual pinball software defaults to for the flipper buttons / magna save buttons.

However with Ratatui there does not seem to be a way to disambiguate modifier keys.

## Solution

Make a difference between left and right modifier keys.

## Notes

If this is not possible by design is there some kind of workaround?

**Comment by joshka** [comment]
Ratatui doesn't handle this part of the equation. That's something to take up with your backend (likely [crossterm](https://github.com/crossterm-rs/crossterm)).

Some links for more info from https://github.com/crossterm-rs/crossterm/issues/685

> The supported events are often even different in each terminal emulator. For background on the extended ways that terminals can report keys see see https://sw.kovidgoyal.net/kitty/keyboard-protocol/ and http://www.leonerd.org.uk/hacks/fixterms/. Crossterm supports the kitty protocol using the [PushKeyboardEnhancementFlags](https://docs.rs/crossterm/latest/crossterm/event/struct.PushKeyboardEnhancementFlags.html) command.

**Comment by francisdb** [comment]
Thanks for the clarification.
