### ISSUE TITLE
Support for larger Buffer size

### ISSUE THREAD

**Issue by kxxt** [ratatui/ratatui#1377]
## Problem

`Rect::new` clips the Rect if the area overflows `u16::MAX`.
But it is very likely that we need to support buffer with area larger than 65536, for example:
- For ultra-wide monitors, it's very likely that 65536 is not enough.
- For offscreen rendering into a large buffer. e.g. `tui-scrollview`.

Note that it is possible to directly create an unclipped `Rect`, creating a buffer with such `Rect` will lead to a `Buffer` with `content` of length `65536`, which will panic at runtime when out of bound access happens. This is a footgun (https://github.com/joshka/tui-widgets/issues/33, https://github.com/ratatui/ratatui/issues/1375) and probably should be fixed regardless of whether we would allow area larger than 65536 in the future.

## Solution

Make a backward incompatible change and use u32 for areas, like following patch. But probably a lot more code need to be edited.

```patch
diff --git a/src/buffer/buffer.rs b/src/buffer/buffer.rs
index 2a509cd..c594eae 100644
--- a/src/buffer/buffer.rs
+++ b/src/buffer/buffer.rs
@@ -256,7 +256,7 @@ impl Buffer {
         // remove offset
         let y = position.y - self.area.y;
         let x = position.x - self.area.x;
-        Some((y * self.area.width + x) as usize)
+        Some(y as u32 * self.area.width as u32 + x as u32)
     }
 
     /// Returns the (global) coordinates of a cell given its index
diff --git a/src/layout/rect.rs b/src/layout/rect.rs
index 9749711..7b86787 100644
--- a/src/layout/rect.rs
+++ b/src/layout/rect.rs
@@ -78,10 +78,10 @@ impl Rect {
         }
     }
 
-    /// The area of the `Rect`. If the area is larger than the maximum value of `u16`, it will be
-    /// clamped to `u16::MAX`.
-    pub const fn area(self) -> u16 {
-        self.width.saturating_mul(self.height)
+    /// The area of the `Rect`.
+    pub const fn area(self) -> u32 {
+        // u16 multiplication cannot overflow u32
+        (self.width as u32) * (self.height as u32)
     }
 
     /// Returns true if the `Rect` has no area.
@@ -546,7 +546,7 @@ mod tests {
             width: 10,
             height: 10,
         };
-        const _AREA: u16 = RECT.area();
+        const _AREA: u32 = RECT.area();
         const _LEFT: u16 = RECT.left();
         const _RIGHT: u16 = RECT.right();
         const _TOP: u16 = RECT.top();
```

## Alternatives

- Do nothing.
- Or lets use u32 for dimensions as well. Maybe in 2077 there will be monitors that could display 65536 characters in a line!

**Comment by joshka** [comment]
Closing in preference to #1375
