### ISSUE TITLE
`assert_eq!` should be consistently used in ratatui

### ISSUE THREAD

**Issue by kdheepak** [ratatui/ratatui#1399]
## Problem

in `./src/layout/layout.rs` we currently use both:

https://github.com/ratatui/ratatui/blob/eff582110be19226c57e5778590cc7a99018e1aa/src/layout/layout.rs#L2529

and 

https://github.com/ratatui/ratatui/blob/eff582110be19226c57e5778590cc7a99018e1aa/src/layout/layout.rs#L1198-L1199

These are inconsistent. 

## Solution

`assert_eq!` should be of the form:

```
assert_eq!(result, expected)
```

**Comment by joshka** [comment]
Rationale: this makes it easy when reading failing test results to understand that the left hand side is always what actually happened while the right hand side is what we expected.

**Comment by farmeroy** [comment]
Hi! I'd be up for this. Would this just be for `./src/layout/layout.rs`?

**Comment by orhun** [comment]
It might exist in other places too but I think updating the `layout.rs` is a good start 👍🏼
