### ISSUE TITLE
Fix Color hsl / hsluv conversions

### ISSUE THREAD

**Issue by joshka** [ratatui/ratatui#1414]
Running a few of the test values through https://www.colorspaceconverter.com/converter/hsluv-to-rgb gives very different numbers, so there's something wrong with this as it stands.

I think it might be better to implement this conversions from palette types instead of as components and to do the same for the hsl conversion.

_Originally posted by @joshka in https://github.com/ratatui/ratatui/issues/1333#issuecomment-2409478621_

**Comment by kdheepak** [comment]
Thanks for checking this!

**Comment by orhun** [comment]
Can you share the values you have tried and the faulty results?

HSL conversion (`from_hsl`) seems to be already using the palette types, so it's not clear to me what you mean by the second point. 🤔

**Comment by joshka** [comment]
The values are in the unit tests.

from_hsl accepts 3 f64 values. I think this should instead accept a single [palette::Hsl](https://docs.rs/palette/latest/palette/struct.Hsl.html) parameter. Likewise from_hsluv should accept palette::Hsluv instead of 3 f64 component values.

**Comment by orhun** [comment]
This will mean that the apps that want to use this feature should also add `palette` as dependency, no? We can possibly export the `palette` crate to make things a bit easier. What do you think?

**Comment by joshka** [comment]
yeah

**Comment by orhun** [comment]
I tried it with a couple of values and they all seem to work for me. For example:

```rs
let color = Color::from_hsluv(400.0, 50.0, 75.0);
assert_eq!(color, Color::Rgb(226, 174, 140));
```

> Converting HSLuv color space to RGB results in:
> rgb(226,174,140) r:226,g:174,b:140 red:226,green:174,blue:140 

Or similarly

```rs
let color = Color::from_hsl(120.0, 50.0, 75.0);
assert_eq!(color, Color::Rgb(159, 223, 159));
```

![image](https://github.com/user-attachments/assets/c3a0229d-7c0d-4428-a947-2d5b368c8172)

From <https://www.rapidtables.com/convert/color/hsl-to-rgb.html>

So I'm not still sure which values were you referring to 🤔

**Comment by joshka** [comment]
Hrm - I must have been looking at the wrong numbers. I'm not sure why. I have confirmed they are indeed correct. My apologies.

**Comment by joshka** [comment]
The second part of this is still relevant (use the palette types as params).

**Comment by orhun** [comment]
Alright, I'm working on it.
