### ISSUE TITLE
hsl / hsluv tests seem flakey

### ISSUE THREAD

**Issue by joshka** [ratatui/ratatui#1433]
## Description

The hsl and hsluv test are flakey (intermittent / environment specific failures).
They fail often on my mac, but not deterministically. They are currently failing on the coverage tests in CI, but not any of the other tests.
I'm not sure what the differences are that would cause this. We don't have a cargo.lock checked in, so this would be worth doing to see how that affects things.

```
❯ cargo test hsl --all-features
   Compiling ratatui v0.28.1 (/Users/joshka/local/ratatui)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 2.93s
     Running unittests src/lib.rs (target/debug/deps/ratatui-bf9a5780c8035ebf)

running 2 tests
test style::color::tests::test_hsl_to_rgb ... FAILED
test style::color::tests::test_hsluv_to_rgb ... FAILED

failures:

---- style::color::tests::test_hsl_to_rgb stdout ----
thread 'style::color::tests::test_hsl_to_rgb' panicked at src/style/color.rs:459:9:
assertion `left == right` failed
  left: Rgb(255, 0, 255)
 right: Rgb(159, 223, 159)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- style::color::tests::test_hsluv_to_rgb stdout ----
thread 'style::color::tests::test_hsluv_to_rgb' panicked at src/style/color.rs:501:9:
assertion `left == right` failed
  left: Rgb(195, 255, 255)
 right: Rgb(255, 255, 255)


failures:
    style::color::tests::test_hsl_to_rgb
    style::color::tests::test_hsluv_to_rgb

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 1896 filtered out; finished in 0.00s

error: test failed, to rerun pass `--lib`
```

## To Reproduce
```shell
cargo test hsl --all-targets
```

## Expected behavior
Success.

## Environment

- OS:
- Terminal Emulator:
- Font:
- Crate version:
- Backend:

**Comment by orhun** [comment]
Maybe this is a `palette` issue? e.g. something related to floating points: https://github.com/Ogeon/palette/issues/21

**Comment by joshka** [comment]
The ranges of values we were passing to create the Hsl and Hsluv were incorrect. Hsl takes 0..1, Hsluv takes 0..100. 🤷 and clamping happens after the conversion when the values are out of range. This seems like not the best idea, as it's like trying to convert 300u16 to u8 and getting 44 instead of 255. That's a valid interpretation, but rarely the intended one.
