### ISSUE TITLE
Through List/TableState method `select_last()` selected entry index only recognized after delay

### ISSUE THREAD

**Issue by lukeflo** [ratatui/ratatui#1475]
## Description
Since upgrading to **v0.29** I recognized that the `ListState`/`TableState` method `select_last()` is really slow during execution. I'm not sure if it is only since the upgrade, but thats when it was obvious to me.

Its not the selection itself which is delayed (the last item is selected without recognizable delay), but the index of the selected item seems to be problematic.

E.g. in my TUI which handles BibLaTeX databases I have a counter in the tables foot area which displays the currently selected entry and the total number of all entries. When selecting the last entry with the mentioned method the counter for the selected entry shows a real high number for some milliseconds (roughly ten digits) before calculating the correct index. Its too fast for an effective screenshot try, but definitely recognizable (at least in `debug` mode with `cargo run`).

A second event where I recognized it is when styling the entries. I use a custom function to dim entries preceding and following the selected entry descending (as [btop](https://github.com/aristocratos/btop) does it in its process list). When again selecting the last entry of the list via `select_last()` method, it takes nearly a second to render the preceding entries correctly. Since calculation inside my function is done using the index of the entries (`.selected().unwrap()` method), there seems to be some delay before the index is rightfully calculated with the `select_last()` method.

## Expected behavior

The calculation of the index should be done immediatley.

I now use a workaround. Instead of the `select_last()` method I use some custom code to calculate the last item. This works just fine and renders everything without delay, even in `debug` mode:

```rust
    pub fn select_last_tag(&mut self) {
        // self.tag_list.tag_list_state.select_last(); // Doesn't work properly after upgrade to ratatui v.0.29
        self.tag_list
            .tag_list_state
            .select(Some(self.tag_list.tag_list_items.len() - 1));
    }
```

## Screenshots

Here is a GIF showing the delayed rendering of the preceding entries. With my custom calculation shown above, the rendering happens immidiatley:

![Image](https://github.com/user-attachments/assets/7e2aec83-2073-4783-b4f7-eaa0e04f708b)

## Environment

- OS: Void Linux
- Terminal Emulator: foot
- Font: Roboto Mono Nerd Font
- Crate version: 0.29
- Backend: crossterm

**Comment by joshka** [comment]
This is called out in the docs as intended behavior. The states don't have any info about how many items there are in the list / table.

> Note: until the list is rendered, the number of items is not known, so the index is set to usize::MAX and will be corrected when the list is rendered

To fix, draw your count after drawing the list / table, to see the updated number. I suspect that you're drawing the selected index before the widget has had a chance to update the state. Maybe we could add an extra sentence to this effect. "If your UI relies pn this ind zbeing accurate, only use the value after rendering has update it.

The alternative (redesign) would be to forgoe statefulwidget for a widget that implements Widget for &mut Table/List and then hide can see the item count. There are various other approaches that would be other possible redesigns however, so I wouldn't suggest this as being the correct approach. It is something you could do in your own app as a wrapper though if you really need the guarantee

**Comment by lukeflo** [comment]
Ok, thanks. I read your cited paragraph, but because it is visible for such a "long" period that I can easily recognize it with my eyes, I thought that might be a bug. Maybe a hint as you suggested might be helpful!

My current workaround is working perfectly fine, so I'll stay with it. Thanks for the clarification.
