### ISSUE TITLE
Context access inside Shape implementation

### ISSUE THREAD

**Issue by renesat** [ratatui/ratatui#1489]
## Problem
I am trying to implement some vector drawing with ratatui, but I face problem. The `ratatui::widgets::canvas::Line` method can't draw a line if one of the points is outside the window. In theory I can calculate the intersection and draw a shorter line, but I need to know the resolution from `Shape`. `get_point` doesn't help because it just returns none if the point is outside. Also `context` is a private field and I don't have access to the required fields.

## Solution

I see few solutions:
- Public access to context in Painter.
- Additional methods like resolution and context bounds
- New property for widgets that need context

## Alternatives

I can use context before calling draw or draw without shape implementation, but it doesn't look consistent.

## Additional context

I can try to implement some of the solution, but I am not sure which way is better

**Comment by joshka** [comment]
Hey there, thanks for raising this issue. It's been a while since I looked at the canvas module, so you're likely more of an expert on this problem than I am right now. I wonder if you could provide a very small example of what doesn't work (i.e. <10 lines), and a few examples of your suggested solutions? It doesn't have to be compiling code, but it would help to make the ideas a little more concrete and assess which one works best.

**Comment by renesat** [comment]
I’m creating a map visualization for my project. The issue is that I'm drawing not by points as in [`ratatui::widgets::canvas::Map`](https://docs.rs/ratatui/latest/ratatui/widgets/canvas/struct.Map.html), but by polygon lines using [`ratatui::widgets::canvas::Line`](https://docs.rs/ratatui/latest/ratatui/widgets/canvas/struct.Line.html). A peculiarity arises here: lines do not render outside of `*_bounds`, even if they pass through the visible area.

You can see the issue in these images:
![Image](https://github.com/user-attachments/assets/65578767-bd09-41d0-adc5-3ca9e30cd74f)
![Image](https://github.com/user-attachments/assets/284ab9c0-d75d-43a1-9829-0fece9716dcd)

Here is a code example that draws a blue line but doesn't draw the red one:
```rust
    let canvas = Canvas::default()
        .marker(Marker::Braille)
        .x_bounds([0.0, 1.0])
        .y_bounds([0.0, 1.0])
        .paint(|ctx| {
            ctx.draw(&ratatui::widgets::canvas::Line {
                x1: 0.5,
                y1: 0.5,
                x2: 2.0,
                y2: 0.0,
                color: Color::Red,
            });
            ctx.draw(&ratatui::widgets::canvas::Line {
                x1: 0.5,
                y1: 0.5,
                x2: 0.9,
                y2: 0.0,
                color: Color::Blue,
            });
        });
    frame.render_widget(canvas, frame.area());
```

I thought about finding the intersections between the visible area and the line and
rendering it:
```rust
            if let Some((start, end)) = crop_line_in_box(start, end, x_bounds, y_bounds) {
                ratatui::widgets::canvas::Line {
                    x1: start.0,
                    y1: start.1,
                    x2: end.0,
                    y2: end.1,
                    color,
                }
                .draw(painter);
            }
```

But the issue is that I need to know `x_bounds` and `y_bounds`. In theory, this information should be available in the [ratatui::widgets::canvas::Painter](https://docs.rs/ratatui/latest/ratatui/widgets/canvas/struct.Painter.html) passed to the `draw` implementation, but this structure does not provide public access to the `Context` where the bounds can be
obtained.

# Proposed Options

1. Rewrite `Line` to render if points are outside the area. The problem is that `Line` also
does not have direct access to the bounds, so they will need to be passed as parameters,
which could slightly slow down rendering.
2. Add methods to access `Context`:
    ```rust
    let context: &Context = painter.context;
    ```
    or access its parts in `Painter`:
    ```rust
    let (x_bound, y_bound) = painter.get_bounds();
    ```
3. Pass `Context` to `Shape::draw` instead of `Painter`. This would break backward
compatibility.
    ```rust
        fn draw(&self, context: &mut Context) {
    ```
4. Add a `draw_with_context` method. This is a more compromise option similar to the third
one.

**Comment by joshka** [comment]
Got it. Thanks for the explanation.
 
1. seems like it breaks the way this works
2. a) (context) Of the methods on Context are there ones which would make things act odd if called from a Shape being drawn? This would likely also entail making the bounds accessible on Context (they're private right now)
2. b) (painter.get_bounds()) This seems like the most reasonable option to me. The terminal width and height don't sounds like they really need to be known by shapes
3. I don't like the idea of breaking backwards compat on this
4. Yeah, 2.b is better

I think it would be worth implementing the painter.get_bounds method. (likely the naming should be just `bounds()`, though it might make sense to make two functions `x_bounds` and `y_bounds` as these are the `new()` params / field names on `context`.

Can you expand on whether there's a likely need for access to the width/height fields in addition to the bounds? (you mentioned resolution above, which would imply this)

**Comment by renesat** [comment]
> Can you expand on whether there's a likely need for access to the width/height fields in addition to the bounds? (you mentioned resolution above, which would imply this)

Sorry. Resolution = bounds in this context. I think area with bounds is enough for shape.

**Comment by renesat** [comment]
And maybe improve the Line method too? Well, if we have access to bounds(), we can render lines with edges outside the area. This is usually how it is done (e.g. cairo and other libraries).

**Comment by joshka** [comment]
This will also make it possible to re-write the circle drawing using the bresenham's / midpoint algorithm. Right now that's a little difficult as the center point and radius are in canvas units, while the algorithm would have to work in grid units. We can get an approximation, but it would snap to the closest grid point to points based on the start the circle rather than choosing the point which should be algorithmically part of the circle. This likely matters if you're trying to move circles around smoothly, but probably is immaterial for most things.

Also, I noticed that the points calculation for the grid points was a tiny bit off when looking into this and fixed that up in https://github.com/ratatui/ratatui/pull/1507. I wonder if you'd mind taking a look for feedback / review?
