### ISSUE TITLE
Documentation improvements for ScrollbarState

### ISSUE THREAD

**Issue by kardwen** [ratatui/ratatui#1493]
## Problem

I think the documentation for `ScrollbarState` could use some improvements. The description of `viewport_content_length` may not be correct.

https://docs.rs/ratatui/latest/ratatui/widgets/struct.ScrollbarState.html

## Solution

I made a draft with documentation changes:

141919559f899fce3d1416dbb5861bea6b39f8d9

**Comment by orhun** [comment]
Thanks for reporting!

Feel free to go ahead and create a PR from your changes :)

**Comment by kardwen** [comment]
I am not 100% sure if I have understood it correctly, need to double check it later

**Comment by joshka** [comment]
> I am not 100% sure if I have understood it correctly, need to double check it later

Feel free to submit your changes as a draft PR and when you're ready. Closing this to reduce the number of places that we're discussing this. Feel free to reopen if there's discussion that you want on this.
