### ISSUE TITLE
ratatui-core/src/text/line.rs and ratatui-core/src/text/text.rs are executable

### ISSUE THREAD

**Issue by sadlerm4** [ratatui/ratatui#1576]
## Description

The Rust source files mentioned in the title are executable. This breaks building ratatui and any Rust crates that depend on ratatui on Fedora and Fedora-based distros. 

This is because rpmbuild by default tries to mangle shebangs in all files that are executable, and doesn't understand that the ``#![attr]`` syntax in Rust (the first line of ratatui-core/src/text/text.rs) is not actually a shebang, so the build fails.

## To Reproduce

Attempt to build ratatui RPM

## Expected behavior

Don't make Rust source files executable.

## Environment

- OS: Fedora Linux
- Terminal Emulator: GNOME Terminal
- Crate version: 0.29.0

## Additional context

A build of a crate that has a ratatui dependency succeeded in July so the change happened sometime between then and now.

**Comment by orhun** [comment]
Good catch! Will be fixed in #1577

We should probably look into why/when this had happened...

**Comment by sadlerm4** [comment]
Thank you so much for the prompt response!

**Comment by joshka** [comment]
There's no obvious attack vector here by marking these as executable (please correct me if I'm wrong and we'll raise an advisory about it). I checked where these come from and it's all the same user:

eb79256ceea151130c6b80930b51098b9ad43f5b
f29c73fb1cf746aea0adfaed4a8b959e0466b830
c69ca47922619332f76488f5d9e70541b496fe1c
a52ee82fc716fafb2652b83a331c36f844104dda

I'm assuming probably some sort of file system issue on their end.
