### ISSUE TITLE
Support hsluv color constructor

### ISSUE THREAD

**Issue by kdheepak** [ratatui/ratatui#763]
## Problem

This will allows developers to define more uniform color palettes like so:

```rust
let GRAY = [
    Color::from_hsluv(235.5, 22.1, 98.2),
    Color::from_hsluv(248.2, 18.5, 96.2),
    Color::from_hsluv(248.3, 16.7, 91.6),
    Color::from_hsluv(243.9, 14.4, 85.1),
    Color::from_hsluv(246.8, 12.5, 66.8),
    Color::from_hsluv(249.7, 15.7, 47.9),
    Color::from_hsluv(245, 25.3, 35.8),
    Color::from_hsluv(248.1, 32.2, 27.3),
    Color::from_hsluv(247.2, 42, 16.3),
    Color::from_hsluv(254, 48.3, 8.3),
]
```

We could use palette as a dependency to handle the conversions

https://crates.io/crates/palette

## Solution

This can be implemented as a constructor on `Color`:

```rust
impl Color {
    fn from_hsluv(h: f64, s: f64, l: f64, a: f64) -> Self {
        let h = h.clamp(0.0, 360.0);
        let s = s.clamp(0.0, 100.0);
        let l = l.clamp(0.0, 100.0);
        let a = a.clamp(0.0, 100.0);
        // TODO: convert to RGB
        Self::Rgb(r, g, b)
    }
}
```

## Alternatives

I'm open to other suggestions for how to enable such a feature.

**Comment by Valentin271** [comment]
I like this idea. But I'd prefer to avoid using palette (or any other deps) just for that.

I'd suggest putting this behind a `palette` feature. I believe most people will still use rgb.

If not to hard, we could also implement it by hand, but didn't really find a clear formula so maybe that's too much.

**Comment by kdheepak** [comment]
My understanding is that it is a series of transformations to go from hsluv to rgb, and I'm assuming we wouldn't want to maintain that.

**Comment by joshka** [comment]
Definitely a feature flash. I recall seeing a create that does more generic conversions like this. I'll find a link later today.

**Comment by orhun** [comment]
I also think that this is a nice feature and we can gate it behind a feature flag for avoiding additional dependencies as default.

**Comment by joshka** [comment]
https://github.com/Canop/coolor was the crate I was thinking of. It's not quite what we're thinking of here though.
I mentioned perhaps doing a Ratatui feature for it in https://github.com/Canop/coolor/issues/2, but never got back to that.

Are there any other crates that already do the conversions between libraries?
