### ISSUE TITLE
Panic in `insert_before` if viewport fills entire screen

### ISSUE THREAD

**Issue by chris-olszewski** [ratatui/ratatui#999]
## Description

It's possible to cause a panic with an `Inline` viewport if it is the size of the screen.  If this happens, then [`max_chunk_size`](https://github.com/ratatui-org/ratatui/blob/main/src/terminal/terminal.rs#L441) will end up being `0` causing [`chunks`](https://doc.rust-lang.org/std/primitive.slice.html#method.chunks) to panic.

## To Reproduce
```
use ratatui::{
    backend::{Backend, CrosstermBackend},
    text::Text,
    widgets::Widget,
    Terminal, TerminalOptions,
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    crossterm::terminal::enable_raw_mode()?;

    let backend = CrosstermBackend::new(std::io::stdout());
    let size = backend.size()?;
    let mut terminal = Terminal::with_options(
        backend,
        TerminalOptions {
            viewport: ratatui::Viewport::Inline(size.height),
        },
    )?;
    terminal.insert_before(1, |buf| Text::raw("Hello World!").render(buf.area, buf))?;

    crossterm::terminal::disable_raw_mode()?;
    Ok(())
}
```

## Expected behavior
Either:
 - Write to a line in the scrollback
 - Error instead of panic

## Environment

- OS: macOS
- Terminal Emulator: iTerm2
- Font: N/A
- Crate version: 0.26.1
- Backend: Crossterm

**Comment by joshka** [comment]
Unfortunately we cant' change things easily to return errors as there are lots of apps that this would break, but we can add new methods that do this (and it's one of those things we've spoken about a few times), so the first option is really orthogonal to this problem. Ideally we should never panic for things that are expected (and sometimes even for things which can be handled by ignoring the problem).

Here, I think this probably should succeed and write the line above the viewport.

Would you consider submitting a PR to fix this?

I'd suggest adding a unit / integration test if possible that shows this panicking and then make that unit test succeed.

**Comment by chris-olszewski** [comment]
> Would you consider submitting a PR to fix this?

Yes! Thanks for the guidance.
